services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - eventware_network

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - eventware_network

networks:
  eventware_network:
    driver: bridge
