name: Formats

on: [ 'push' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.4 ]
        dependency-version: [ prefer-stable ]

    name: Formats PHP${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, mongodb
          tools: prestissimo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Coding Linter Checks
        run: composer test:lint

      - name: Coding PHPStan Types Check
        run: composer test:types

      - name: Coding PHPMess Check
        run: composer test:mess

      - name: Coding Rector Check
        run: composer test:refacto
